services:
  - type: web
    name: nigeria-blood-bank
    runtime: java
    rootDir: blood-bank
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/blood-bank-1.0.0.jar
    plan: free
    envVars:
      - key: DB_HOST
        value: db.dfnwamdsvrnujxxnlzjp.supabase.co
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: postgres
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: TERMII_API_KEY
        value: test
      - key: CLOUDINARY_CLOUD_NAME
        value: test
      - key: CLOUDINARY_API_KEY
        value: test
      - key: CLOUDINARY_API_SECRET
        value: test